"use client"
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/component/GlobalSpeedDial"
import GlobalSpeedDial from "@/component/GlobalSpeedDial";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function SpeedDial() {
  return (
    <div className="fab">
      {/* a focusable div with tabIndex is necessary to work on all browsers. role="button" is necessary for accessibility */}
      <div tabIndex={0} role="button" className="btn btn-lg btn-circle btn-success">F</div>

      {/* buttons that show up when FAB is open */}
      <div>Label B <button className="btn btn-lg btn-circle">A</button></div>
      <div>Label C <button className="btn btn-lg btn-circle">B</button></div>
      <div>Label D <button className="btn btn-lg btn-circle">C</button></div>
    </div>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        {children}
        <GlobalSpeedDial/>

      </body>
    </html>
  );
}
